[tool.poetry]
name = "ELF_RSS"
version = "2.0.0"
description = "ELF_RSS"
authors = ["Quan666"]
license = "GPL v3"
readme = "README.md"
packages = [
    { include = "ELF_RSS2", from = "src/plugins" },
    { include = "ELF_URL", from = "src/plugins" },    
]
homepage = "https://github.com/Quan666/ELF_RSS"
repository = "https://github.com/Quan666/ELF_RSS"
keywords = ["nonebot", "nonebot2", "rss" ,"elf" ,"rsshub"]

[tool.poetry.dependencies]
python = "^3.7"
nonebot2 = "^2.0.0a8.post2"
nb-cli = "^0.3.1"
nonebot-plugin-apscheduler = "^0.1.0"

[tool.poetry.dev-dependencies]
nonebot-test = "^0.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
